// <auto-generated />
namespace CollectiveBook.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class peopleadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(peopleadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201603212256084_people-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
